### ISSUE TITLE
Specific tree set loading

### ISSUE THREAD

**Issue by tmcgowan** [TreeScaper/CloudforestVisualization#6]
One of the really powerful aspects of NLDR for phylogenetics is the ability to load tree sets where different subsets of the trees come from different sources (e.g., different genes or different types of analyses) and then color the points based on the source to see if they occupy different regions of tree space. However, it doesn’t seem like that functionality is currently available in CloudForest.

**Comment by tmcgowan** [comment]
@jembrown I want to make this a priority enhancement. Here is my understanding of the functionality (in a very cookbook style):

1. There can be multiple NLDR coordinate outputs (3D) where each NLDR output is based on a separate tree distance input file
1. User chooses the first NLDR coordinate file for visualizing (this is arbitrary)
1. From the 2d/3d visualization, user should be able to choose any other NLDR 3d coordinate file from history and overlay that file into the existing visualization
1. Each NLDR import will appear with its own color

I can do this, just want to fully understand  the enhancement.
Also, I will need some data for testing.

**Comment by jembrown** [comment]
@tmcgowan Thanks, that would be great if this was a priority.

I think the way this needs to be done is to create one single NLDR projection from one input tree set, because the projected coordinates actually depend on the trees in the set (i.e., separate projections can't just be overlaid). Separately, users can specify a series of indices (corresponding to different subsets of the trees) that allow them to assign specific colors. In the old GUI version of TreeScaper, this could be done in a few different ways:

(1) Manually specifying individual indices (separated with commas) or ranges of indices
(2) Setting a series of "steps" - every n trees has its own color
(3) Loading a file with pre-specified sets of indices (written as in (1))

In the old GUI, the colors were then automatically assigned according to one of two possible color schemes, but it would be even better if the colors themselves could be individually specified.

**Comment by tmcgowan** [comment]
@jembrown Thanks for the clarification. Duh, projections among different NLDR files are not related. I can do this, and I will work on this enhancement now.

**Comment by jembrown** [comment]
@tmcgowan Great, thanks!

**Comment by tmcgowan** [comment]
Done in commit 44b4c19d11d997ff2ea5055185107bca72211f6d
